#### general settings
gpu_ids: [ 0 ]
classes: ["NOCOVID", "COVID"]
num_classes: &num_classes 1
threshold: 0.5

#### datasets
datasets:
  mode: CardioSpike
  train:
    dataset_args:
      path_to_csv: /home/malchul/work/CadrioSpike/data/train_split.csv
    n_workers: 10
    batch_size: 32
    augs_args:
      add_sampling: True


  val:
    dataset_args:
      path_to_csv: /home/malchul/work/CadrioSpike/data/val_split.csv
    n_workers: 5
    batch_size: 1
    augs_args: null

network:
  model: CRNN
  input_channels: 1
  output_channels: *num_classes
  start_channels: 32
  num_convs: 10
  multiplier: 1.3

# Maps output from dataset to model args
input_keys:
  ampl: x
  mask: mask
  time: time
  ampl_diff: x_diff
  angle: angle

exp_name: ""
#### path
pretrained_checkpoint_path: null
checkpoint_path: null

#### training settings: learning rate scheme, loss
train:

  scheduler_params:
    scheduler: ExponentialLR  # Registry keyword for scheduler name
    gamma: 0.995405417351527  # Reduces by 20

  optimizer_params:
    optimizer: AdamW
    lr: !!float 5e-5
    weight_decay: 0.001
    betas: [ 0.9, 0.999 ]

  loss_args:
    criterion: LocalBetterLoss

  epoches: 500
  use_negative_sampling: False


  use_plt: False

  log_freq: 10
  img_log_freq: 400
  val_freq: 1
  val_steps_limit: 1.0
  train_steps_limit: 1000


  precision: 32
  gradient_clip_val: 0


hydra:
  run:
    dir: outputs_finetune/${now:%Y-%m-%d}/${now:%H-%M-%S}_${exp_name}